[program.test1]
directory = "/Users/bounce/Documents/gowork/src/github.com/iampastor/supergo/tools/http_listener"
command = "./http_listener -arg=test1  hello"
auto_restart = true
stdout_logfile = ""
stderr_logfile = ""
max_retry = 3
listen_addrs = [":4042"]
stop_timeout = 10