[program.test]
directory = "/Users/bounce/Documents/gowork/src/github.com/iampastor/supervisor/tools/http_listener"
command = " ./http_listener -arg=test world"
auto_restart = true
stdout_file = "/tmp/hello.log"
stderr_file = "/tmp/hello.err"
max_retry = 3
listen_addrs = [":4041"]
stop_timeout = 10

[include]
files = "config/subconfig/*.toml"